//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taken
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekening
    {
        public string RekeningNr { get; set; }
        public int KlantNr { get; set; }
        public decimal Saldo { get; set; }
        public string Soort { get; set; }
    
        public virtual Klant Klant { get; set; }

        //1.6 overschrijven: voorbeeldoplossing (zie ook Program)
        public void Overschrijven(Rekening naarRekening, decimal bedrag)
        {
            if (this.Saldo < bedrag)
            {
                throw new SaldoOntoereikendException();
            }
            else
            {
                this.Saldo -= bedrag;
                naarRekening.Saldo += bedrag;
            }
        }
    }
}
